# Generated by Django 5.1.1 on 2024-10-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_category_options_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_offer',
            field=models.BooleanField(default=False),
        ),
    ]
