# Generated by Django 5.1.1 on 2024-10-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_product_has_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_arrivals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
